# Generated by Django 5.1.6 on 2025-05-19 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('anthracnose', 'Anthracnose'), ('dendritic_spot', 'Dendritic Spot')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='Start typing address…', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_hectares', models.FloatField(blank=True, help_text='Optional: site area', null=True)),
                ('stocking_rate', models.FloatField(blank=True, help_text='Optional: plants per hectare', null=True)),
                ('number_plants', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
                ('number_surveyed', models.PositiveIntegerField(help_text='How many plants you inspected')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total minutes spent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mango_app.pestdisease')),
                ('plant_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mango_app.plantpart')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
