# Generated by Django 5.1.6 on 2025-05-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mango_app', '0001_initial'),
    ]

    operations = [
    ]
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('Mango_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='grower',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.deletion.CASCADE,
                default=1,    # <-- you must supply a default or allow null
            ),
            preserve_default=False,
        ),
    ]